package com.aj.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.aj.database.TASKINFO;
import com.aj.database.TEMPLETTABLE;
import com.aj.database.SAMPLINGTABLE;

import com.aj.database.TASKINFODao;
import com.aj.database.TEMPLETTABLEDao;
import com.aj.database.SAMPLINGTABLEDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tASKINFODaoConfig;
    private final DaoConfig tEMPLETTABLEDaoConfig;
    private final DaoConfig sAMPLINGTABLEDaoConfig;

    private final TASKINFODao tASKINFODao;
    private final TEMPLETTABLEDao tEMPLETTABLEDao;
    private final SAMPLINGTABLEDao sAMPLINGTABLEDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tASKINFODaoConfig = daoConfigMap.get(TASKINFODao.class).clone();
        tASKINFODaoConfig.initIdentityScope(type);

        tEMPLETTABLEDaoConfig = daoConfigMap.get(TEMPLETTABLEDao.class).clone();
        tEMPLETTABLEDaoConfig.initIdentityScope(type);

        sAMPLINGTABLEDaoConfig = daoConfigMap.get(SAMPLINGTABLEDao.class).clone();
        sAMPLINGTABLEDaoConfig.initIdentityScope(type);

        tASKINFODao = new TASKINFODao(tASKINFODaoConfig, this);
        tEMPLETTABLEDao = new TEMPLETTABLEDao(tEMPLETTABLEDaoConfig, this);
        sAMPLINGTABLEDao = new SAMPLINGTABLEDao(sAMPLINGTABLEDaoConfig, this);

        registerDao(TASKINFO.class, tASKINFODao);
        registerDao(TEMPLETTABLE.class, tEMPLETTABLEDao);
        registerDao(SAMPLINGTABLE.class, sAMPLINGTABLEDao);
    }
    
    public void clear() {
        tASKINFODaoConfig.getIdentityScope().clear();
        tEMPLETTABLEDaoConfig.getIdentityScope().clear();
        sAMPLINGTABLEDaoConfig.getIdentityScope().clear();
    }

    public TASKINFODao getTASKINFODao() {
        return tASKINFODao;
    }

    public TEMPLETTABLEDao getTEMPLETTABLEDao() {
        return tEMPLETTABLEDao;
    }

    public SAMPLINGTABLEDao getSAMPLINGTABLEDao() {
        return sAMPLINGTABLEDao;
    }

}
