package com.aj.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TASKINFO".
 */
public class TASKINFO {

    private Long taskID;
    private String task_name;
    private String task_letter;
    private Boolean is_finished;
    private Boolean is_new_task;
    private Long download_time;
    private String description;

    public TASKINFO() {
    }

    public TASKINFO(Long taskID) {
        this.taskID = taskID;
    }

    public TASKINFO(Long taskID, String task_name, String task_letter, Boolean is_finished, Boolean is_new_task, Long download_time, String description) {
        this.taskID = taskID;
        this.task_name = task_name;
        this.task_letter = task_letter;
        this.is_finished = is_finished;
        this.is_new_task = is_new_task;
        this.download_time = download_time;
        this.description = description;
    }

    public Long getTaskID() {
        return taskID;
    }

    public void setTaskID(Long taskID) {
        this.taskID = taskID;
    }

    public String getTask_name() {
        return task_name;
    }

    public void setTask_name(String task_name) {
        this.task_name = task_name;
    }

    public String getTask_letter() {
        return task_letter;
    }

    public void setTask_letter(String task_letter) {
        this.task_letter = task_letter;
    }

    public Boolean getIs_finished() {
        return is_finished;
    }

    public void setIs_finished(Boolean is_finished) {
        this.is_finished = is_finished;
    }

    public Boolean getIs_new_task() {
        return is_new_task;
    }

    public void setIs_new_task(Boolean is_new_task) {
        this.is_new_task = is_new_task;
    }

    public Long getDownload_time() {
        return download_time;
    }

    public void setDownload_time(Long download_time) {
        this.download_time = download_time;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
