package com.aj.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEMPLETTABLE".
 */
public class TEMPLETTABLE {

    private Long templetID;
    private Long taskID;
    private String templet_name;
    private String templet_content;
    private Long download_time;

    public TEMPLETTABLE() {
    }

    public TEMPLETTABLE(Long templetID) {
        this.templetID = templetID;
    }

    public TEMPLETTABLE(Long templetID, Long taskID, String templet_name, String templet_content, Long download_time) {
        this.templetID = templetID;
        this.taskID = taskID;
        this.templet_name = templet_name;
        this.templet_content = templet_content;
        this.download_time = download_time;
    }

    public Long getTempletID() {
        return templetID;
    }

    public void setTempletID(Long templetID) {
        this.templetID = templetID;
    }

    public Long getTaskID() {
        return taskID;
    }

    public void setTaskID(Long taskID) {
        this.taskID = taskID;
    }

    public String getTemplet_name() {
        return templet_name;
    }

    public void setTemplet_name(String templet_name) {
        this.templet_name = templet_name;
    }

    public String getTemplet_content() {
        return templet_content;
    }

    public void setTemplet_content(String templet_content) {
        this.templet_content = templet_content;
    }

    public Long getDownload_time() {
        return download_time;
    }

    public void setDownload_time(Long download_time) {
        this.download_time = download_time;
    }

}
