package com.aj.collection.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.aj.collection.database.SAMPLINGTABLE;
import com.aj.collection.database.TASKINFO;
import com.aj.collection.database.TEMPLETTABLE;

import com.aj.collection.database.SAMPLINGTABLEDao;
import com.aj.collection.database.TASKINFODao;
import com.aj.collection.database.TEMPLETTABLEDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sAMPLINGTABLEDaoConfig;
    private final DaoConfig tASKINFODaoConfig;
    private final DaoConfig tEMPLETTABLEDaoConfig;

    private final SAMPLINGTABLEDao sAMPLINGTABLEDao;
    private final TASKINFODao tASKINFODao;
    private final TEMPLETTABLEDao tEMPLETTABLEDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sAMPLINGTABLEDaoConfig = daoConfigMap.get(SAMPLINGTABLEDao.class).clone();
        sAMPLINGTABLEDaoConfig.initIdentityScope(type);

        tASKINFODaoConfig = daoConfigMap.get(TASKINFODao.class).clone();
        tASKINFODaoConfig.initIdentityScope(type);

        tEMPLETTABLEDaoConfig = daoConfigMap.get(TEMPLETTABLEDao.class).clone();
        tEMPLETTABLEDaoConfig.initIdentityScope(type);

        sAMPLINGTABLEDao = new SAMPLINGTABLEDao(sAMPLINGTABLEDaoConfig, this);
        tASKINFODao = new TASKINFODao(tASKINFODaoConfig, this);
        tEMPLETTABLEDao = new TEMPLETTABLEDao(tEMPLETTABLEDaoConfig, this);

        registerDao(SAMPLINGTABLE.class, sAMPLINGTABLEDao);
        registerDao(TASKINFO.class, tASKINFODao);
        registerDao(TEMPLETTABLE.class, tEMPLETTABLEDao);
    }
    
    public void clear() {
        sAMPLINGTABLEDaoConfig.clearIdentityScope();
        tASKINFODaoConfig.clearIdentityScope();
        tEMPLETTABLEDaoConfig.clearIdentityScope();
    }

    public SAMPLINGTABLEDao getSAMPLINGTABLEDao() {
        return sAMPLINGTABLEDao;
    }

    public TASKINFODao getTASKINFODao() {
        return tASKINFODao;
    }

    public TEMPLETTABLEDao getTEMPLETTABLEDao() {
        return tEMPLETTABLEDao;
    }

}
