package com.aj.collection.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Unique;

/**
 * Entity mapped to table "TASKINFO".
 */
@Entity
public class TASKINFO {
    @Unique
    private Long taskID;
    private String task_name;
    private String task_letter;
    private Boolean is_finished;
    private Boolean is_new_task;
    private Long download_time;
    private String description;
    @Generated(hash = 90444219)
    public TASKINFO(Long taskID, String task_name, String task_letter, Boolean is_finished,
            Boolean is_new_task, Long download_time, String description) {
        this.taskID = taskID;
        this.task_name = task_name;
        this.task_letter = task_letter;
        this.is_finished = is_finished;
        this.is_new_task = is_new_task;
        this.download_time = download_time;
        this.description = description;
    }
    @Generated(hash = 2114347557)
    public TASKINFO() {
    }
    public Long getTaskID() {
        return this.taskID;
    }
    public void setTaskID(Long taskID) {
        this.taskID = taskID;
    }
    public String getTask_name() {
        return this.task_name;
    }
    public void setTask_name(String task_name) {
        this.task_name = task_name;
    }
    public String getTask_letter() {
        return this.task_letter;
    }
    public void setTask_letter(String task_letter) {
        this.task_letter = task_letter;
    }
    public Boolean getIs_finished() {
        return this.is_finished;
    }
    public void setIs_finished(Boolean is_finished) {
        this.is_finished = is_finished;
    }
    public Boolean getIs_new_task() {
        return this.is_new_task;
    }
    public void setIs_new_task(Boolean is_new_task) {
        this.is_new_task = is_new_task;
    }
    public Long getDownload_time() {
        return this.download_time;
    }
    public void setDownload_time(Long download_time) {
        this.download_time = download_time;
    }
    public String getDescription() {
        return this.description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
}
