package com.aj.collection.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Unique;

/**
 * Entity mapped to table "TEMPLETTABLE".
 */
@Entity
public class TEMPLETTABLE {
    @Unique
    @Id(autoincrement = true)
    private Long templetID;
    private Long taskID;
    private String templet_name;
    private String templet_content;
    private Long download_time;
    @Generated(hash = 965592665)
    public TEMPLETTABLE(Long templetID, Long taskID, String templet_name, String templet_content,
            Long download_time) {
        this.templetID = templetID;
        this.taskID = taskID;
        this.templet_name = templet_name;
        this.templet_content = templet_content;
        this.download_time = download_time;
    }
    @Generated(hash = 647082824)
    public TEMPLETTABLE() {
    }
    public Long getTempletID() {
        return this.templetID;
    }
    public void setTempletID(Long templetID) {
        this.templetID = templetID;
    }
    public Long getTaskID() {
        return this.taskID;
    }
    public void setTaskID(Long taskID) {
        this.taskID = taskID;
    }
    public String getTemplet_name() {
        return this.templet_name;
    }
    public void setTemplet_name(String templet_name) {
        this.templet_name = templet_name;
    }
    public String getTemplet_content() {
        return this.templet_content;
    }
    public void setTemplet_content(String templet_content) {
        this.templet_content = templet_content;
    }
    public Long getDownload_time() {
        return this.download_time;
    }
    public void setDownload_time(Long download_time) {
        this.download_time = download_time;
    }
}
